import { useEffect, useState } from 'react';
import { useI18n } from '../context/I18nContext';
import { api } from '../services/api';

export default function SterilizationPage() {
  const { t } = useI18n();
  const [cycles, setCycles] = useState<any[]>([]);
  const [form, setForm] = useState({ equipment: '', cycleNumber: '', cycleDate: new Date().toISOString().slice(0, 10), temperature: '', durationMinutes: '', operator: '', result: 'passed', observations: '' });
  const load = () => api.getSterilization().then((data) => setCycles(data || [])).catch(() => {});
  useEffect(() => { load(); }, []);
  const save = async () => { if (!form.equipment || !form.cycleNumber || !form.operator) return; try { await api.createSterilization({ ...form, temperature: Number(form.temperature) || undefined, durationMinutes: Number(form.durationMinutes) || undefined }); setForm({ ...form, cycleNumber: '', observations: '' }); load(); } catch {} };
  return <div className="space-y-4"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white">{t('sterilization.title')}</h1><p className="text-sm text-muted mt-1">{t('sterilization.subtitle')}</p></div><div className="card"><h2 className="text-lg font-semibold mb-4">{t('sterilization.newCycle')}</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{([['equipment','text'],['cycleNumber','text'],['cycleDate','date'],['temperature','number'],['durationMinutes','number'],['operator','text']] as const).map(([key,type]) => <div key={key}><label className="field-label">{t(`sterilization.${key}`)}</label><input className="input" type={type} value={(form as any)[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></div>)}<div><label className="field-label">{t('sterilization.result')}</label><select className="input" value={form.result} onChange={(e) => setForm({ ...form, result: e.target.value })}><option value="passed">{t('sterilization.passed')}</option><option value="failed">{t('sterilization.failed')}</option><option value="pending">{t('sterilization.pending')}</option></select></div></div><textarea className="input mt-4" rows={3} placeholder={t('sterilization.observations')} value={form.observations} onChange={(e) => setForm({ ...form, observations: e.target.value })} /><button className="btn-primary mt-4" onClick={save}>{t('common.save')}</button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{cycles.map((cycle) => <div className="card" key={cycle.id}><div className="flex justify-between"><h2 className="font-semibold">{cycle.equipment}</h2><span className="badge">{cycle.result}</span></div><p className="text-sm text-muted mt-2">{cycle.cycle_number} · {cycle.cycle_date}</p><p className="text-sm text-muted">{cycle.temperature || '—'} °C · {cycle.duration_minutes || '—'} min · {cycle.operator || '—'}</p></div>)}</div></div>;
}
